---
output: word_document
---
#The strength of migratory connectivity affects demography of two Neotropical migratory songbirds

Michael T. Hallworth^1,3^, T. Scott Sillett^1^ , Nicholas L. Rodenouse^2^ and Peter P. Marra^1^    


^1^ Smithsonian Conservation Biology Institute's Migartory Bird Center, Washington, D.C. 20008    

^2^ Wellesley College, Wellesley, MA.    

^3^ mhallworth@gmail.com    



##Abstract

&nbsp;&nbsp;&nbsp;&nbsp;Understanding how the annual cycle of migratory songbirds shapes demography and population dynamics necessitates that we know where individuals are throughout the year. The miniaturization of archival tracking technology such as light-level geolocators and GPS units has allowed researchers to make direct links between the different phases of the annual cycle. We deployed archival light-level geolocators on two migratory songbirds breeding within Hubbard Brook Experimental Forest, N.H. to quantify the strength of migratory connectivity and identify where they spend the non-breeding season. We then used remotely sensed data of their wintering locations to make inferences about how climatic factors experienced during the non-breeding season correlate with demographic parameters the subsequent breeding season. We found that both the Black throated Blue warbler Warbler and the Ovenbird exhibit moderate connectivity with the majority of individuals wintering on the islands of Cuba and Hispaniola. The amount of precipitation on the islands of Cuba and Hispaniola during the non-breeding season (Nov-May) was positively correlated with demographic parameters at both local (plot-level) and landscape (watershed) scales. These findings suggest that environmental conditions experienced throughout the annual cycle contribute to variation in demographic rates observed on the breeding grounds. Demographic studies of linked populations during both the breeding and non-breeding grounds will greatly improve our understanding of how seasonal interactions shape populations and ultimately how populations respond to a changing climate.

## Introduction 

1) Set up the question - why important to understant Migratory Connectivity to understand demographics

&nbsp;&nbsp;&nbsp;&nbsp; The degree to which demography and population dynamics of migratory animals is affected by conditions experienced throughout annual cycle is poorly understood. In part, because it requires the ability to track individuals and populations throughout the year to quantify the strength of migratory connectivity or the geographic link between breeding, migratory and non-breeding periods. Therefore, in order to fully understand demography and population dynamics of migartory animals knowledge of where individuals and populations are throughout the year is needed. Our ability to track such animals is improving rapidly and has allowed researchers to begin to quantify migratory connectivity. However, the role that the strength of migratory connectivity plays in driving demography and population dynamics remains unknown and is essential for our understanding of migratory populations and conserving migratory species.  

2) What we know about seasonal interactions and carry-over effects - set up forest loss and precipitation gradient

&nbsp;&nbsp;&nbsp;&nbsp;Mounting evidence through the use of indirect techniques supports that the phases of the annual cycle are inextricably linked and conditions and/or events experienced by individuals carry-over to influence subsequent phases of the annual cycle. Carry-over effects from the non-breeding season can have a profound affect on annual survival, dispersal distance, timing of arrival and reproductive success during the subsequent breeding season. Many of these carry-over effects at the individual-level are either directly or indirectly mediated by precipitation and it's impact on habitat quality during the non-breeding period. However, population level consequences (seasonal interactions) are difficult to quantify because the non-breeding locations and the strength of migratory connectivity are typically unknown. 

3) Lay out the questions - two species same study area different connectivity 

&nbsp;&nbsp;&nbsp;&nbsp; The strength of migratory connectivity is an important factor influencing the degree that seasonal interactions play in shaping demography and population dynamics. The role of seasonal interactions is likely stronger in populations that exhibit strong connectivity and are more diffuse in populations with weak connectivity. Here, we test the role that migratory connectivity plays in demography and population dynamics using two long-distance migratory songbird species breeding at Hubbard Brook Experimental Forest, N.H. We used archival light-level geolocators and a combination of light-level geolocators and GPS tags to determine the strength of migratory connectivity for Black-throated Blue Warblers (Setophaga ceruealens) and the Ovenbird (Seiurus aurocapilla), respectively. We tested to role that migratory connectivity plays on the strength of seasonal interactions using 1) plot-level demographic data measured using marked populations and 2) landscape-level demographic data determined through point-count survey data. 



1) Recruitment
2) Survival




